# fly.toml app configuration file generated for authgrid-api on 2025-10-28T08:18:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'authgrid-api'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  AUTHGRID_DOMAIN = 'authgrid.net'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
